-- 1. Delete existing entries
DELETE FROM band;

-- 2. Reset auto-increment ID (MySQL syntax)
ALTER TABLE band AUTO_INCREMENT = 1;

-- 3. Add `created_at` column if not exists
-- ALTER TABLE band
--     ADD COLUMN IF NOT EXISTS created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- 4. Insert 83 bands with random created_at in past 7 days
INSERT INTO band (name, genre, description, created_at) VALUES
('The Beatles', 'Rock', 'Legendary English rock band from the 1960s.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('Queen', 'Rock', 'British rock band known for powerful vocals and theatrical shows.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('Pink Floyd', 'Progressive Rock', 'Famous for conceptual albums and psychedelic sound.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('Led Zeppelin', 'Rock', 'British rock pioneers known for heavy guitar riffs.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('Nirvana', 'Grunge', 'Seattle grunge band that defined a generation.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('Radiohead', 'Alternative Rock', 'Experimental alternative rock band from Oxfordshire.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('The Rolling Stones', 'Rock', 'Legendary rock band formed in the 1960s.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('The Who', 'Rock', 'Known for their rock operas and energetic performances.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('AC/DC', 'Hard Rock', 'Australian hard rock legends.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('U2', 'Alternative Rock', 'Irish band with a strong political and social voice.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('Coldplay', 'Alternative Rock', 'British rock band known for melodic songs.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('Metallica', 'Metal', 'American heavy metal band formed in 1981.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('Green Day', 'Punk Rock', 'American punk rock band from California.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('Red Hot Chili Peppers', 'Funk Rock', 'Funk-infused rock from Los Angeles.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('Foo Fighters', 'Alternative Rock', 'Rock band founded by Nirvana’s drummer.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('The Strokes', 'Indie Rock', 'New York garage rock revivalists.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('Muse', 'Alternative Rock', 'British rock band blending electronic and classical sounds.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('Imagine Dragons', 'Pop Rock', 'Popular American band blending rock and electronic.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('Linkin Park', 'Nu Metal', 'Famous for blending metal and hip-hop.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('Blink-182', 'Pop Punk', 'California-based punk band known for humor and energy.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('The Killers', 'Alternative Rock', 'Las Vegas band known for synth-driven anthems.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('Arctic Monkeys', 'Indie Rock', 'Sheffield band with sharp lyrics and cool swagger.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('Paramore', 'Pop Punk', 'Female-fronted rock band with an emotional edge.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('The 1975', 'Pop Rock', 'English band blending pop and indie rock.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('Daft Punk', 'Electronic', 'French electronic music duo.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('The Smiths', 'Indie Rock', 'Iconic British band with poetic lyrics.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('Oasis', 'Britpop', '1990s Britpop legends.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('Fleetwood Mac', 'Rock', 'Anglo-American rock group known for Rumours.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('The Doors', 'Psychedelic Rock', 'L.A. band led by Jim Morrison.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('Joy Division', 'Post-Punk', 'Manchester band with dark and atmospheric sound.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('Kings of Leon', 'Alternative Rock', 'Southern-influenced rock band from Tennessee.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('System of a Down', 'Metal', 'Armenian-American political metal band.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('The Cure', 'Goth Rock', 'Melancholic and iconic UK rock band.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('The Smashing Pumpkins', 'Alternative Rock', '90s alternative rock band with theatrical style.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('Pearl Jam', 'Grunge', 'Seattle grunge legends.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('Bon Jovi', 'Rock', 'American rock band known for power ballads.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('The Clash', 'Punk', 'Political punk pioneers from the UK.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('Guns N'' Roses', 'Hard Rock', 'Wild and iconic rock band from L.A.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('The Kinks', 'Rock', 'British Invasion band known for storytelling.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('The Police', 'Rock', 'Band with reggae influence and Sting on vocals.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('KISS', 'Hard Rock', 'Face-painted rock legends.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('Genesis', 'Progressive Rock', 'UK prog rock band that launched Phil Collins.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('Tool', 'Progressive Metal', 'Dark, cerebral, and heavy band from California.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('Tame Impala', 'Psychedelic Rock', 'Australian psychedelic solo project.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('Electric Light Orchestra', 'Rock', 'Band known for orchestral arrangements.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('Panic! at the Disco', 'Alternative Rock', 'Theatrical pop rock band.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('R.E.M.', 'Alternative Rock', 'American pioneers of college rock.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('Beastie Boys', 'Hip Hop Rock', 'Hip-hop trio with punk roots.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('Fall Out Boy', 'Pop Punk', 'Pop punk band with emo flair.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('The Beach Boys', 'Pop Rock', 'American band famous for vocal harmonies.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('The Velvet Underground', 'Art Rock', 'Influential experimental rock band from New York.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('Florence + The Machine', 'Indie Rock', 'Ethereal and dramatic music from the UK.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('LCD Soundsystem', 'Dance Punk', 'Electronic-infused rock with sharp lyrics.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('Nine Inch Nails', 'Industrial Rock', 'Dark industrial rock project by Trent Reznor.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('Portugal. The Man', 'Psychedelic Rock', 'Experimental band blending rock and synths.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('The National', 'Indie Rock', 'Emotive baritone vocals and moody instrumentals.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('Alt-J', 'Indie Electronic', 'Unique math-pop indie band from Leeds.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('CHVRCHES', 'Synthpop', 'Scottish band with bright synth-driven pop.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('Arcade Fire', 'Indie Rock', 'Grand orchestral indie rock from Canada.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('Vampire Weekend', 'Indie Pop', 'Whimsical and catchy indie from New York.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('The War on Drugs', 'Heartland Rock', 'Atmospheric rock blending Americana and synth.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('Interpol', 'Post-Punk Revival', 'Moody and stylish NYC post-punk band.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('MGMT', 'Psychedelic Pop', 'Surreal and nostalgic synth-pop duo.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('The xx', 'Indie Pop', 'Minimalist London band with intimate vocals.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('Yeah Yeah Yeahs', 'Garage Rock', 'Dynamic indie trio led by Karen O.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('Modest Mouse', 'Indie Rock', 'Jittery rhythms and offbeat lyrics.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('The Shins', 'Indie Pop', 'Dreamy and melodic indie from New Mexico.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('Foals', 'Indie Rock', 'Energetic and rhythm-heavy rock band.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('Franz Ferdinand', 'Post-Punk', 'Danceable guitar-driven indie rock.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('Bastille', 'Indie Pop', 'British band known for dramatic pop anthems.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('Of Monsters and Men', 'Indie Folk', 'Icelandic group with sweeping choruses.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('The Lumineers', 'Folk Rock', 'Rustic American folk-rock duo.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('Kaleo', 'Blues Rock', 'Icelandic band blending rock and soul.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('Snow Patrol', 'Alternative Rock', 'Emotional rock ballads from Northern Ireland.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('The Script', 'Pop Rock', 'Dublin trio mixing rock and R&B.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('OneRepublic', 'Pop Rock', 'Radio-ready anthemic American pop rock.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('Mumford & Sons', 'Folk Rock', 'Banjo-led British folk rock quartet.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('Walk the Moon', 'Indie Pop', 'Energetic American pop band.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('Two Door Cinema Club', 'Electropop', 'Danceable indie rock from Northern Ireland.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('Milky Chance', 'Folk Pop', 'German duo blending folk and electronic.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('Hozier', 'Blues Rock', 'Soulful Irish singer-songwriter.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY),
('Greta Van Fleet', 'Hard Rock', 'Modern rock band with retro Led Zeppelin sound.', NOW() - INTERVAL FLOOR(RAND() * 7) DAY);
